import {StyleSheet} from 'react-native';
import {scale} from '~/utils/scaling';
import {Colors, FontSizes, FontWeights} from '~/theme/theme';

export default StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: scale(40),
  },
  container: {
    flex: 1,
    paddingTop: scale(60),
    paddingHorizontal: scale(20),
    alignItems: 'center',
  },
  logoSection: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: scale(26),
  },
  logoWrapper: {
    width: scale(120),
    height: scale(120),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    marginBottom: scale(16),
  },
  logoGradient: {
    width: scale(80),
    height: scale(80),
    borderRadius: scale(999),
    alignItems: 'center',
    justifyContent: 'center',
  },
  shieldUserIcon: {
    width: scale(42),
    height: scale(42),
    color: Colors.white,
  },
  logoRing: {
    position: 'absolute',
    width: scale(100),
    height: scale(100),
    borderRadius: scale(999),
    borderWidth: 2,
    borderColor: Colors.borderAccent,
  },
  logoRingOuter: {
    position: 'absolute',
    width: scale(120),
    height: scale(120),
    borderRadius: scale(999),
    borderWidth: 1,
    borderColor: Colors.borderGlow,
  },
  logoParticle: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.accentPurple,
  },
  title: {
    fontSize: FontSizes.xlarge,
    fontWeight: FontWeights.black,
    color: Colors.primary,
    marginBottom: scale(8),
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: FontSizes.small,
    color: Colors.textMuted,
    textAlign: 'center',
    paddingHorizontal: scale(32),
    lineHeight: 20,
  },
  userHeader: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    padding: scale(16),
    borderRadius: scale(16),
    borderWidth: 1,
    marginBottom: scale(24),
    borderColor: Colors.border,
    backgroundColor: Colors.deepBackground,
  },
  userAvatar: {
    width: scale(58),
    height: scale(58),
    borderRadius: scale(32),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(16),
    overflow: 'hidden',
  },
  avatar: {
    width: '100%',
    height: '100%',
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    color: Colors.textPrimary,
    fontSize: FontSizes.semiLarge,
    fontWeight: FontWeights.bold,
    marginBottom: scale(4),
  },
  userAddress: {
    color: Colors.textMuted,
    fontSize: FontSizes.small,
  },
  featuresContainer: {
    width: '100%',
    marginBottom: scale(20),
  },
  featureCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.deepBackground,
    borderRadius: scale(16),
    padding: scale(16),
    marginBottom: scale(12),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  featureIconContainer: {
    width: scale(56),
    height: scale(56),
    borderRadius: scale(999),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: scale(16),
  },
  featureContent: {
    flex: 1,
  },
  featureTitle: {
    fontSize: FontSizes.regular,
    fontWeight: FontWeights.bold,
    color: Colors.textPrimary,
    marginBottom: scale(4),
  },
  featureDescription: {
    fontSize: FontSizes.small,
    color: Colors.textMuted,
    lineHeight: 18,
  },
  connectButtonContainer: {
    width: '100%',
    marginBottom: scale(20),
  },
  connectedContainer: {
    width: '100%',
    marginTop: scale(20),
  },
  connectedGradient: {
    borderRadius: scale(24),
    padding: scale(24),
    backgroundColor: Colors.deepBackground,
    marginBottom: scale(16),
    borderWidth: 1,
    borderColor: Colors.border,
  },
  connectedTitle: {
    fontSize: FontSizes.xlarge,
    fontWeight: FontWeights.black,
    color: Colors.success,
    textAlign: 'center',
    marginBottom: scale(24),
  },
  infoCard: {
    marginBottom: scale(20),
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: scale(12),
  },
  infoLabel: {
    color: Colors.textPrimary,
    fontSize: FontSizes.small,
    fontWeight: FontWeights.bold,
    marginLeft: scale(6),
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  addressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: scale(12),
    paddingHorizontal: scale(12),
    borderRadius: scale(12),
    backgroundColor: Colors.mutedBackground,
  },
  addressText: {
    fontSize: FontSizes.medium,
    fontWeight: FontWeights.bold,
    color: Colors.accentBlue,
    letterSpacing: 0.5,
  },
  copyButton: {
    padding: scale(8),
    backgroundColor: 'rgba(28, 81, 254, 0.15)',
    borderRadius: scale(8),
  },
  balanceAmount: {
    fontSize: FontSizes.huge,
    fontWeight: FontWeights.black,
    color: Colors.textPrimary,
    marginBottom: scale(4),
  },
  chainText: {
    fontSize: FontSizes.large,
    fontWeight: FontWeights.bold,
    color: Colors.textPrimary,
  },
  logoutButton: {
    backgroundColor: Colors.error,
  },
});
